apiVersion: v1
kind: Service
metadata:
  name: landing
  labels:
    app: landing
spec:
  ports:
    - port: 80
  selector:
    app: landing
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  labels:
    app: landing
spec:
  selector:
    matchLabels:
      app: landing
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: landing
        tier: frontend
    spec:
      containers:
      - image: dana2cr/landingpage:v1
        name: landing
        ports:
        - containerPort: 80
          name: landing
        resources:
          requests:
            cpu: 50m
            memory: 50m
